### ISSUE TITLE
如何兼容umeng多渠道统计？

### ISSUE THREAD

**Issue by dongweiq** [baoyongzhang/ApkChannelBuilder#1]
如题，如何兼容umeng多渠道统计？
 <meta-data
            android:name="UMENG_APPKEY"
            android:value="${UMENG_APPKEY_VALUE}"/>
        <meta-data
            android:name="UMENG_CHANNEL"
            android:value="${UMENG_CHANNEL_VALUE}"/>
友盟是在androidMenifest.xml文件中填写对应的统计值的

**Comment by baoyongzhang** [comment]
友盟可以在代码里设置渠道吧

**Comment by laogong** [comment]
怎么运行啊？

**Comment by EasonHolmes** [comment]
渠道列表有格式要求吗？我写了UMENG_CHANNEL但对应的value并没有改变

**Comment by baoyongzhang** [comment]
@laogong 可以去 release 里面下载

**Comment by baoyongzhang** [comment]
@EasonHolmes 回车换行分隔多个渠道。你是从 META-INF 下面取得渠道吗

**Comment by EasonHolmes** [comment]
@baoyongzhang 我是通过反编译看的AndroidManifest文件中的值

**Comment by baoyongzhang** [comment]
@EasonHolmes 我没说过这个工具会修改 Manifest，README 里说明了这是在 META-INF 写入空文件的方案，请你先了解这种多渠道方案。
