### ISSUE TITLE
如何安装并运行

### ISSUE THREAD

**Issue by daiwenbo88** [baoyongzhang/ApkChannelBuilder#2]
你好 刚买MAC不久 想弱弱的问一句 这个怎么安装到mac电脑上。

**Comment by baoyongzhang** [comment]
你可以去 [release](https://github.com/baoyongzhang/ApkChannelBuilder/releases) 下在编译好的，双击就能运行

**Comment by bingoogolapple** [comment]
![image](https://cloud.githubusercontent.com/assets/8949716/21558997/5f001786-ce7e-11e6-8daa-da6558bb6a81.png)
